oauth2-server: additional information about token
clouway/oauth2-server pull request #29
Opened 2017-03-29 10:50 UTC by qnislavnachev

additional info added to token such as email and client id

Related to #7

2017-03-29 10:55 UTC, mgenov requested changes

2017-03-29 10:55 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/TokenInfoController.java
> +    o.addProperty("azp", token.clientId);
It would be better IdentityFinder to be taken in the TokenInfoController instead of Tokens implementation is it won't force change on clients.

2017-03-29 11:02 UTC, mgenov commented
It would be better if issueToken method accepts Identity object instead of just identityId. In this case client implementations of tokens would be able to store in the persistence/cache layer all properties which latter to be returned in the token response. 

The IssueNewTokenActivity is taking identity
```java
Authorization authorization = possibleResponse.get();

TokenResponse response = tokens.issueToken(GrantType.AUTHORIZATION_CODE, client, authorization.identityId, authorization.scopes, instant);
if (!response.isSuccessful()) {
  return OAuthError.invalidRequest("Token cannot be issued.");
}
```

So the Identity could be taken here as authorization is performed only once whether information about token can be executed many times and oauth2-server will gain performance benefit.

2017-03-29 14:59 UTC, qnislavnachev commented
issueToken accepts Identity object instead string of identity id and no longer client should inject IdentityFinder in Tokens Implementation

2017-03-30 07:12 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/jwt/JwtController.java
> +import com.clouway.oauth2.*;
You have to fix your IDEA settings in the Code Style section: 

<img width="783" alt="screen shot 2017-03-30 at 10 10 25 am" src="https://cloud.githubusercontent.com/assets/209223/24491722/2e5c9ccc-1531-11e7-8cae-cfab734ba78b.png">

Make "Class count to use *" 12 
Make "Name count to use static imports with *" 12

2017-03-30 07:37 UTC, qnislavnachev commented
IDEA settings fixed 
![style](https://cloud.githubusercontent.com/assets/20161493/24492644/d98b4c44-1534-11e7-9bc1-f5ca64eb45cf.png)

2017-03-30 07:38 UTC, mgenov approved these changes
LGTM !

2017-03-30 07:39 UTC, merged