oauth2-server: added certificate availability check
clouway/oauth2-server pull request #47
Opened 2017-04-12 07:40 UTC by VasilMitovClouway

Id_token no longer created in IssueNewTokenActivity if there are no certificates configured.
related #45

2017-04-12 07:41 UTC, VasilMitovClouway commented
Cannot add labels or assign reviewers.

2017-04-12 07:43 UTC, mgenov requested changes

2017-04-12 07:43 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> -
I'm not able to see test for the new behaviour.

2017-04-12 07:50 UTC, VasilMitovClouway commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> -
```java
@Test
  public void publicCertificatesNotConfigured() throws Exception {
    IssueNewTokenActivity controller = new IssueNewTokenActivity(tokens, identityFinder, clientAuthorizationRepository, keyStore);
    final Client client = aNewClient().build();
    final DateTime anyTime = new DateTime();
    final Identity identity = aNewIdentity().withId("::user_id::").build();

    context.checking(new Expectations() {{
      oneOf(clientAuthorizationRepository).findAuthorization(with(any(Client.class)), with(any(String.class)));
      will(returnValue(Optional.of(new Authorization("", "", "::user_id::", "::auth_code::", Collections.<String>emptySet(), Collections.singleton("::redirect_uri::")))));

      oneOf(tokens).issueToken(GrantType.AUTHORIZATION_CODE, client, identity, Collections.<String>emptySet(), anyTime);
      will(returnValue(new TokenResponse(true, aNewToken().withValue("::token::").build(), "::refresh token::")));

      oneOf(identityFinder).findIdentity(with(any(String.class)), with(any(GrantType.class)), with(any(DateTime.class)));
      will(returnValue(Optional.of(identity)));

      oneOf(keyStore).publicCertificates();
      will(returnValue(Collections.emptyMap()));
    }});

    Response response = controller.execute(client, new ParamRequest(ImmutableMap.of("code", "::auth_code::", "redirect_uri", "::redirect_uri::")), anyTime);
    String body = new RsPrint(response).printBody();

    assertThat(body, containsString("::token::"));
  }
```

The thing is that this test is an absolute copy of the happy path and I didnt think it was informative enought to be added.

2017-04-12 07:55 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> -
It indicates a smell in the code as this check need to be performed here which actually need to be considered.

2017-04-12 08:05 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> -
Keep in mind that signing need to be performed by private keys and verification to be performed with public keys, which means that name of the method is misleading and requires some fixes.

2017-04-12 08:06 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> -
The second comment is not going to be addressed here unless you see it as reasonable to be here.

2017-04-19 08:23 UTC, VasilMitovClouway commented
Regarding the availability check, we had a discussion about the ClientKeyStore.certificates() to return a Certificate object. Here is an example implementation of the Certificate Object and a helper class CertificateParcer

```java
public class Certificate {
  public final String certId;
  public final String privatePem;
  public final String publicPem;

  public Certificate(String certId, String privatePem, String publicPem) {
    this.certId = certId;
    this.privatePem = privatePem;
    this.publicPem = publicPem;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (o == null || getClass() != o.getClass()) return false;
    Certificate that = (Certificate) o;
    return Objects.equal(certId, that.certId) &&
            Objects.equal(privatePem, that.privatePem) &&
            Objects.equal(publicPem, that.publicPem);
  }

  @Override
  public int hashCode() {
    return Objects.hashCode(certId, privatePem, publicPem);
  }
}
```
```java
public class CertificateParcer {

  public static PrivateKey getPrivateKey(Certificate certificate) {
    Block block = getPemBlock(certificate.privatePem);
    return (PrivateKey) getKey("private",block);
  }

  public static PublicKey getPublicKey(Certificate certificate) {
    Block block = getPemBlock(certificate.privatePem);
    return (PublicKey) getKey("public",block);
  }

  public static Pem.Block getPrivatePem(Certificate certificate) {
    return getPemBlock(certificate.privatePem);
  }

  public static Pem.Block getPublicPem(Certificate certificate) {
    return getPemBlock(certificate.publicPem);
  }

  private static Key getKey(String type,Block block){
    try {
      PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(block.getBytes());
      KeyFactory kf = KeyFactory.getInstance("RSA");
      switch (type){
        case "private":return kf.generatePrivate(keySpec);
        case "public":return kf.generatePublic(keySpec);
      }
    } catch (NoSuchAlgorithmException|InvalidKeySpecException e) {
      e.printStackTrace();
    }
    return null;
  }

  private static Block getPemBlock(String pemString) {
    Pem pem = new Pem();
    try {
      Pem.Block block = pem.parse(new ByteArrayInputStream(pemString.getBytes()));
      return block;
    } catch (IOException e) {
      e.printStackTrace();
    }
    return null;
  }
}
```

2017-04-19 10:13 UTC, mgenov commented
Maybe it would be better client apps to pass PrivateKey and PublicKey objects directly instead of PEM. This will let them decide in what form to be persisted. 

About this design, it's not visible how this code is going to be used by the IssueNewTokenActivity. The problem there is that it has many dependencies which causes tests to blow.

2017-04-19 10:19 UTC, mgenov commented
About the Certificate Class: 

Keep in mind that Java already has such classes:
https://docs.oracle.com/javase/7/docs/api/java/security/cert/Certificate.html
https://docs.oracle.com/javase/7/docs/api/java/security/cert/X509Certificate.html

and there is a difference between private/public key and certificate (certificate adds additional information about the owner of the certificate). It would be better library to support certificates instead of simple keys.

Take a look at: 
https://www.googleapis.com/oauth2/v1/certs

As you can see it serves CERTIFICATES, not keys.

2017-04-19 13:51 UTC, VasilMitovClouway commented
I think now the tests are more readable. Moved the keystore.privateCertificates() a bit lower, because it is not needed to be done when Oauth.error is returned shortening a few tests and it is now easier to read the tests when certificates are not returned after #55 .

2017-04-19 14:02 UTC, mgenov requested changes

2017-04-19 14:02 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> +  public void idTokenNotReturnedWhenCertificatesNotImplemented() throws Exception {
noPrivateCertsAreConfigured

2017-04-19 14:02 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/client/CertificatesNotConfiguredException.java
> +public class CertificatesNotConfiguredException extends RuntimeException {
This exception is not used.

2017-04-19 14:02 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/IssueNewTokenActivity.java
> +    if (available(certificates)) {
I'm not sure that null check need to be added. It's bad practices methods to return null but we cannot relay on correct behaviour from client apps. 

if is readable if it's inline:

```java
if (certificates != null && !certificates.isEmpty()) {

}
```

2017-04-19 14:06 UTC, VasilMitovClouway commented on oauth2-server/src/test/java/com/clouway/oauth2/IssueNewTokenForClientTest.java
> +  public void idTokenNotReturnedWhenCertificatesNotImplemented() throws Exception {
Tried to be as specific as I can in the description. Name is now changed

2017-04-19 14:07 UTC, VasilMitovClouway commented on oauth2-server/src/main/java/com/clouway/oauth2/client/CertificatesNotConfiguredException.java
> +public class CertificatesNotConfiguredException extends RuntimeException {
Leftover exception that was a part of my ideas for solving the chaos that were the tests. Removed.

2017-04-19 14:08 UTC, VasilMitovClouway commented on oauth2-server/src/main/java/com/clouway/oauth2/IssueNewTokenActivity.java
> +    if (available(certificates)) {
removed private method and moved the checks inline. We have tested this if block, and it fixes the bug that occurred last week

2017-04-19 14:20 UTC, mgenov approved these changes
LGTM !

2017-04-19 14:21 UTC, merged