oauth2: public keys are served from endpoint
clouway/oauth2-server pull request #69
Opened 2017-06-30 14:57 UTC by qnislavnachev

public key now are served publicly by given HTTP endpoint, they
are return as list

Fixed #38

2017-06-30 15:02 UTC, mgenov requested changes

2017-06-30 15:02 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/RetrievePublicKeysTest.java
> +    String body = CharStreams.toString(new InputStreamReader(response.body(), Charsets.UTF_8));
There is a RsPrint class about this.

2017-06-30 15:02 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/PublicCertsController.java
> +    o.add("publicKeys", getAsJsonArray(keyList));
The generated JSON message doesn't look like the prosed in the issue. 


```javascript
{
   "keyid1": "keybody1", 
   "keyid2": "keybody2"
}
```

2017-06-30 15:03 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/RetrievePublicKeysTest.java
> +  public void publicKeysIsE() throws Exception {
isE?

2017-06-30 15:08 UTC, qnislavnachev commented
I am sorry PR is not ready for review yet.. my bad

2017-07-01 11:30 UTC, qnislavnachev commented
PR is ready for review. Comments was fixed.

2017-07-01 11:39 UTC, qnislavnachev commented
There is some issue with the continuous integration server that I will check

2017-07-01 11:42 UTC, mgenov requested changes

2017-07-01 11:42 UTC, mgenov commented on oauth2-server/src/main/java/com/clouway/oauth2/PublicKeys.java
> +public interface PublicKeys {
Add comments to this public interface, as it's going to be used by client code which need to know what's the purpose of it.

2017-07-01 11:42 UTC, mgenov commented on oauth2-server/src/test/java/com/clouway/oauth2/RetrievePublicKeysTest.java
> +    Map<String, String> keys = new HashMap<String, String>() {{
Use sorted map like TreeMap to ensure that order is preserved.

2017-07-01 11:57 UTC, qnislavnachev commented
PR notes fixed need another review.

2017-07-01 11:59 UTC, mgenov approved these changes
LGTM !

2017-07-01 11:59 UTC, merged